id: A5EEBD988
title: 'Wellspring of Bounty for the Fortunate: A Guru Yoga of the Three Family Lords'
type: translation
pechas:
- IBC3052DE
- IC37AFF01
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:01.951755
  last_modified_at: 2023-01-04 12:33:01.951768
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IBC3052DE/EB49: 993F
  IC37AFF01/7C9B: 993F
